# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 411))
        self.tabWidget.setStyleSheet("background-color:rgb(167, 167, 167);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.txt_nome = QtWidgets.QLineEdit(self.tab_5)
        self.txt_nome.setGeometry(QtCore.QRect(10, 40, 151, 21))
        self.txt_nome.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_nome.setObjectName("txt_nome")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label.setStyleSheet("font-famiy:\"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.txt_estado = QtWidgets.QLineEdit(self.tab_5)
        self.txt_estado.setGeometry(QtCore.QRect(10, 220, 151, 21))
        self.txt_estado.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_estado.setObjectName("txt_estado")
        self.txt_patrimonio = QtWidgets.QLineEdit(self.tab_5)
        self.txt_patrimonio.setGeometry(QtCore.QRect(10, 100, 151, 21))
        self.txt_patrimonio.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_patrimonio.setObjectName("txt_patrimonio")
        self.txt_email = QtWidgets.QLineEdit(self.tab_5)
        self.txt_email.setGeometry(QtCore.QRect(10, 160, 151, 21))
        self.txt_email.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_email.setObjectName("txt_email")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_2.setStyleSheet("font-famiy:\"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 31, 21))
        self.label_3.setStyleSheet("font-famiy:\"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 41, 21))
        self.label_4.setStyleSheet("font-famiy:\"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.Btn_botao1_2 = QtWidgets.QPushButton(self.tab_5)
        self.Btn_botao1_2.setGeometry(QtCore.QRect(40, 290, 71, 31))
        self.Btn_botao1_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"\n"
"font-famiy:\"Small Fonts\";\n"
"font-size: 12pt")
        self.Btn_botao1_2.setObjectName("Btn_botao1_2")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_nome.setText(_translate("MainWindow", "Giulia Nunes Vargas de Lima"))
        self.label.setText(_translate("MainWindow", "Nome"))
        self.txt_estado.setText(_translate("MainWindow", "Rio de Janeiro"))
        self.txt_patrimonio.setText(_translate("MainWindow", "Monitor"))
        self.txt_email.setText(_translate("MainWindow", "giuliavargas2001@gmail.com"))
        self.label_2.setText(_translate("MainWindow", "Patrimonio"))
        self.label_3.setText(_translate("MainWindow", "E-mail"))
        self.label_4.setText(_translate("MainWindow", "Estado"))
        self.Btn_botao1_2.setText(_translate("MainWindow", "Exibir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
