# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 691, 411))
        self.tabWidget.setStyleSheet("background-color:rgb(167, 167, 167);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.txt_patrimonio = QtWidgets.QLineEdit(self.tab_5)
        self.txt_patrimonio.setGeometry(QtCore.QRect(10, 21, 61, 21))
        self.txt_patrimonio.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_patrimonio.setText("")
        self.txt_patrimonio.setObjectName("txt_patrimonio")
        self.label_patrimonio = QtWidgets.QLabel(self.tab_5)
        self.label_patrimonio.setGeometry(QtCore.QRect(11, 0, 61, 21))
        self.label_patrimonio.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_patrimonio.setObjectName("label_patrimonio")
        self.txt_memoria = QtWidgets.QLineEdit(self.tab_5)
        self.txt_memoria.setGeometry(QtCore.QRect(10, 149, 151, 21))
        self.txt_memoria.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_memoria.setText("")
        self.txt_memoria.setObjectName("txt_memoria")
        self.txt_modelo = QtWidgets.QLineEdit(self.tab_5)
        self.txt_modelo.setGeometry(QtCore.QRect(10, 63, 151, 21))
        self.txt_modelo.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_modelo.setText("")
        self.txt_modelo.setObjectName("txt_modelo")
        self.txt_processador = QtWidgets.QLineEdit(self.tab_5)
        self.txt_processador.setGeometry(QtCore.QRect(10, 107, 151, 21))
        self.txt_processador.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_processador.setText("")
        self.txt_processador.setObjectName("txt_processador")
        self.label_modelo = QtWidgets.QLabel(self.tab_5)
        self.label_modelo.setGeometry(QtCore.QRect(12, 42, 41, 21))
        self.label_modelo.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_modelo.setObjectName("label_modelo")
        self.label_processador = QtWidgets.QLabel(self.tab_5)
        self.label_processador.setGeometry(QtCore.QRect(11, 86, 61, 21))
        self.label_processador.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_processador.setObjectName("label_processador")
        self.label_memoria = QtWidgets.QLabel(self.tab_5)
        self.label_memoria.setGeometry(QtCore.QRect(12, 128, 51, 21))
        self.label_memoria.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_memoria.setObjectName("label_memoria")
        self.btn_buscar = QtWidgets.QPushButton(self.tab_5)
        self.btn_buscar.setGeometry(QtCore.QRect(80, 21, 41, 21))
        self.btn_buscar.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font-family:\"Small Fonts\";\n"
"\n"
"font-size: 10pt")
        self.btn_buscar.setObjectName("btn_buscar")
        self.btn_3pontos = QtWidgets.QPushButton(self.tab_5)
        self.btn_3pontos.setGeometry(QtCore.QRect(130, 316, 31, 21))
        self.btn_3pontos.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"\n"
"font-family:\"Small Fonts\";\n"
"font-size: 12pt\n"
"")
        self.btn_3pontos.setObjectName("btn_3pontos")
        self.txt_status = QtWidgets.QLineEdit(self.tab_5)
        self.txt_status.setGeometry(QtCore.QRect(11, 191, 151, 21))
        self.txt_status.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_status.setText("")
        self.txt_status.setObjectName("txt_status")
        self.txt_setor = QtWidgets.QLineEdit(self.tab_5)
        self.txt_setor.setGeometry(QtCore.QRect(11, 278, 151, 21))
        self.txt_setor.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_setor.setText("")
        self.txt_setor.setObjectName("txt_setor")
        self.txt_usuario = QtWidgets.QLineEdit(self.tab_5)
        self.txt_usuario.setGeometry(QtCore.QRect(11, 235, 151, 21))
        self.txt_usuario.setStyleSheet("background-color:rgb(254, 254, 254);")
        self.txt_usuario.setText("")
        self.txt_usuario.setObjectName("txt_usuario")
        self.label_setor = QtWidgets.QLabel(self.tab_5)
        self.label_setor.setGeometry(QtCore.QRect(13, 257, 31, 21))
        self.label_setor.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_setor.setObjectName("label_setor")
        self.label_usuario = QtWidgets.QLabel(self.tab_5)
        self.label_usuario.setGeometry(QtCore.QRect(13, 212, 41, 21))
        self.label_usuario.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_usuario.setObjectName("label_usuario")
        self.label_status = QtWidgets.QLabel(self.tab_5)
        self.label_status.setGeometry(QtCore.QRect(13, 170, 41, 21))
        self.label_status.setStyleSheet("font-family:\"MS Shell Dlg 2\";")
        self.label_status.setObjectName("label_status")
        self.btn_mostrar = QtWidgets.QPushButton(self.tab_5)
        self.btn_mostrar.setGeometry(QtCore.QRect(64, 316, 51, 21))
        self.btn_mostrar.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font-family:\"Small Fonts\";\n"
"\n"
"font-size: 10pt")
        self.btn_mostrar.setObjectName("btn_mostrar")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_patrimonio.setText(_translate("MainWindow", "Patrimonio:"))
        self.label_modelo.setText(_translate("MainWindow", "Modelo:"))
        self.label_processador.setText(_translate("MainWindow", "Processador:"))
        self.label_memoria.setText(_translate("MainWindow", "Memoria:"))
        self.btn_buscar.setText(_translate("MainWindow", "Buscar"))
        self.btn_3pontos.setText(_translate("MainWindow", "..."))
        self.label_setor.setText(_translate("MainWindow", "Setor:"))
        self.label_usuario.setText(_translate("MainWindow", "Usuario:"))
        self.label_status.setText(_translate("MainWindow", "Status:"))
        self.btn_mostrar.setText(_translate("MainWindow", "Mostrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
