# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Btn_botao1 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_botao1.setGeometry(QtCore.QRect(234, 222, 131, 61))
        self.Btn_botao1.setStyleSheet("background-color:rgb(255, 0, 255);\n"
"\n"
"font-famiy:\"Small Fonts\";\n"
"font-size: 12pt")
        self.Btn_botao1.setObjectName("Btn_botao1")
        self.txt_campo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_campo.setGeometry(QtCore.QRect(430, 230, 171, 41))
        self.txt_campo.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.txt_campo.setObjectName("txt_campo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_botao1.setText(_translate("MainWindow", "Botão1"))
